### PR TITLE
Parallelize the processing of LeaderAndIsr requests

### PR DESCRIPTION
**Pull request by gitlw**
The reason for this change is explained in https://issues.apache.org/jira/browse/KAFKA-10734
This PR tries to speedup the processing of the LeaderAndISR request by running the processing among different fetcher threads in parallel. Specifically this PR leverages the scala [parallel collections API](https://docs.scala-lang.org/overviews/parallel-collections/overview.html) to run the processing in multiple scala background threads.
Internally the scala parallel collections API divides the items in the collection among the multiple background threads, and if some thread finishes faster while the other threads have work remaining, there could be work-stealing among the background threads. More details can be found in the [paper](https://infoscience.epfl.ch/record/165523/files/techrep.pdf).

During testing, we found this technique could lead to a deadlock during the dynamic config change on the "num.replica.fetchers" property. The deadlock happens between the scala background thread and the change-event-process-thread responsible for processing zk config changes (stacktrace of these threads attached [here](https://docs.google.com/document/d/18Ypo4LxW9krtgXvAbAnFEDXW1TWg7eSXyiFNXXdsUEo/edit?usp=sharing)).
As an easy way to get around this problem, this PR proposes to disable the config change on the "num.replica.fetchers" property.

Using the added benchmark code, it shows the time to process the very first LeaderAndIsr request with 10,000 partitions (in a 100 broker cluster with num.replace.fetchers=2) on a follower broker is reduced from 22+ seconds to 5+ seconds

** baseline
Benchmark                                                           (brokerCount)  (numReplicaFetchers)  (partitionsCount)  Mode  Cnt      Score   Error  Units
ReplicaFetcherBecomeFollowerBenchmark.testProcessFirstLeaderAndIsr            100                     2              10000    ss    2  22981.726          ms/op

** parallel execution
Benchmark                                                           (brokerCount)  (numReplicaFetchers)  (partitionsCount)  Mode  Cnt     Score   Error  Units
ReplicaFetcherBecomeFollowerBenchmark.testProcessFirstLeaderAndIsr            100                     2              10000    ss    2  5189.689          ms/op

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by smccauliff** [comment]
Does this use the default, system-wide, fork-join pool?  If so this should use it's own thread pool. It's hard to know what the default  thread pool will be used for and any change to the Kafka broker code can potentially access that thread pool and do horrible things like blocking I/O ; the leader and isr requests may never be processed if that happens.

**Comment by gitlw** [comment]
@smccauliff Thanks for the suggestion. It seems that won't be an issue in this particular case since 1) there should be no other logic using the scala background threads given this is the first time I'm adding the scala parallel collections library; 2) currently the LeaderAndIsr request is being processed using the request-handler-thread, which is also being used for handling produce and consume requests (without enabling KIP-291).

In any case, I like your suggestion, and think it's a safer thing to do. Thus the separate forkjoin pool has been added.

**Comment by smccauliff** [comment]
Thanks.  I will sleep better at night.

**Comment by gitlw** [comment]
Closing this PR since the changes have been split into smaller PRs.

**Pull request closed without merging**
