### PR TITLE
[LI-HOTFIX] LIKAFKA-49108: Include topic names and/or broker IDs in ApiError exception messages

### PR DESCRIPTION
**Pull request by groelofs**
Existing broker-side API errors, including the very common UNKNOWN_TOPIC_OR_PARTITION, do not include relevant information about the error such as the topic name in question or the broker reporting the error. This can lead to particularly confusing client-side logs with no hints about the specific problem:

```
2022/12/14 18:26:30.961 ERROR [KafkaMonitoring] [Thread-36] [kafka-monitoring] [] Error when running KafkaMonitoringThread. System.exit() will be called.
java.lang.reflect.InvocationTargetException: null 
    at jdk.internal.reflect.GeneratedConstructorAccessor90.newInstance(Unknown Source) ~[?:?]
    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
    [...]
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
    at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45) ~[kafka-clients-2.4.1.65.jar:?]
    [...]
```

This change adds such basic information for unknown topics, authorization errors, topics about to be deleted, etc.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by gitlw** [comment]
The changes LGTM.
I think we should also augment the client side to print the topic name, e.g.
https://github.com/linkedin/kafka/blob/f9ae407108f59b74f18a1acdc12ccec2cab662c1/clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java#L1992

**Review by mhratson — APPROVED** [review]
LGTM

**Comment by groelofs** [comment]
> The changes LGTM. I think we should also augment the client side to print the topic name, e.g.
> 
> https://github.com/linkedin/kafka/blob/f9ae407108f59b74f18a1acdc12ccec2cab662c1/clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java#L1992

Good suggestion--done, thanks. Rerunning full tests, but :core:test passes, aside from flakes. (I'll see if we can squeeze in some code-quality work in the coming quarter; there are quite a few of them in core.)

**Review by gitlw — APPROVED** [review]
Thanks for this improvement!

**Pull request merged**
